[package]
name = "sweeper-3d"
version = "0.1.4"
edition = "2024"

[dependencies]
bevy = { version = "0.17", default-features = false, features = [
    "bevy_gltf",
    "bevy_asset",
    "bevy_audio",
    "bevy_winit",
    "bevy_render",
    "bevy_text",
    "bevy_pbr",
    "bevy_state",
    "png",
    "hdr",
    "vorbis",
    "x11",
    "tonemapping_luts",
    "default_font",
] }
bevy_egui = "0.38"
egui_extras = { version = "0.33", features = ["svg"] }
ndarray = "0.16"
rand = "0.9"
log = "0.4"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

# Optimize release build for size
[profile.release]
opt-level = 's'

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[features]
debug-draw = ["bevy/bevy_gizmos"]
